package Seção_2;

public class Aula_29 {
	
	// RECORD SAO "CLASSES", UTILIZADAS COMO DTO, QUE SAO OBJETOS DE TRANSFERENCIA DE DADOS 
	// SAO CLASSES FINALS, ENTAO NAO PODEMOS CRIAR HERANÇA
	// SEUS METODOS SAO IMUTAVEIS, A ATRIBUIÇÃO APENAS POR CONSTRUTOR
	
	

}
