package Seção_2;

public class Aula_27 {

	/* OBJETOS SAO VARIAVEIS QUE RECEBEM UM TIPO CRIADO PELO USUARIO
	 SE O USUARIO CRIAR UMA CLASSE DO TIPO PESSOA, VARIAVEIS CRIADAS COM O TIPO
	 PESSOA SE TORNAM OBJETOS
	 PODEMOS LEVAR COMO EXEMPLO QUE A CLASSE É UMA FORMA, ATRIBUTOS SAO OS
	 IGREDIENTES E MISTURANDO IGREDIENTES E COLOCANDO EM UMA FORMA DO TIPO BOLO
	 TEMOS BOLO COMO RESULTADO*/
}
