package Seção_1;

public class Aula_11 {

	// MODIFICADOR DE ACESSO
	
	/* SAO PALAVRAS RESERVADAS QUE IMPOE REGRAS DE VISIBILIDADE/ACESSO A ELEMENTOS COMO CLASSES, VARIAVEIS, CONSTANTES E METODOS
	  
	  CONHECIDOS COMO 
	  
	  PUBLIC  APLICA SE A AOS 4 ELEMENTOS
	  PRIVATE APLICA SE A VARIAVEIS, CONSTANTES E METODOS
	  PROTECTED APLICA SE A VARIAVEIS, CONSTANTES E METODOS
	  DEFAULT/PACKAGE APLICA SE A AOS 4 ELEMENTOS
	  
	  PUBLIC    - SUA REGRA DE VISIBILIDADE DIZ QUE QUAL QUER CLASSE DE QUAL QUER PACOTE TEM ACESSO AO ELEMENTO 
	  PRIVATE   - SUA REGRA DE VISIBILIDADE DIZ QUE SOMENTE A PROPRIA CLASSE TEM ACESSO AO ELEMENTO 
	  PROTECTED - SUA REGRA DE VISIBILIDADE DIZ SÓ TEM ACESSO AO ELEMENTO QUEM FAZ PARTE DA "FAMILIA" OU SEJA HERANÇA  
	  DEFAULT/PACKAGE - SUA REGRA DE VISIBILIDADE DIZ O ACESSO AO ELEMENTO É LIBERADO A QUEM FAZ PARTE DO MESMO PACOTE 
	  
	  
	  OUTROS MODIFICADORES MAS NAO DE ACESSO E SIM DE COMPORTAMENTOS DE CLASSE
	  
	  
	  FINAL
	  ABSTRACT
	  
	  FINAL DECRETA QUE NAO PODE SER HERDADO 
	  
	  ABSTRACT NAO PODE SER INSTANCIADA (CRIAR OBJETOS)
	  
	  SEUS METODOS NAO POSSUI CORPO APENAS A ASSINATURA
	  
	  
	  CLASSES ABSTRATAS SÓ SERVE PARA SEREM SUPERCLASSES E SUAS SUBCLASSES QUE IMPLEMENTA SUA LOGICA
	  
	 */
	
}