package Seção_1;

public class Aula_11 {

	// MODIFICADOR DE ACESSO
	
	/* SAO PALAVRAS RESERVADAS QUE IMPOE REGRAS DE VISIBILIDADE/ACESSO A ELEMENTOS COMO CLASSES, VARIAVEIS, CONSTANTES E METODOS
	  
	  CONHECIDOS COMO 
	  
	  PUBLIC
	  PRIVATE
	  PROTECTED
	  DEFAULT/PACKAGE
	  
	  PUBLIC    - SUA REGRA DE VISIBILIDADE DIZ QUE QUAL QUER CLASSE DE QUAL QUER PACOTE TEM ACESSO AO ELEMENTO 
	  PRIVATE   - SUA REGRA DE VISIBILIDADE DIZ QUE SOMENTE A PROPRIA CLASSE TEM ACESSO AO ELEMENTO 
	  PROTECTED - SUA REGRA DE VISIBILIDADE DIZ SÓ TEM ACESSO AO ELEMENTO QUEM FAZ PARTE DA "FAMILIA" OU SEJA HERANÇA  
	  DEFAULT/PACKAGE - SUA REGRA DE VISIBILIDADE DIZ O ACESSO AO ELEMENTO É LIBERADO A QUEM FAZ PARTE DO MESMO PACOTE 
	  
	 */
	
}