package Seção_1;

public class Aula_16_Lab {

	

		/*
		 
		 	OPERADORES SAO SIMBOLOS ESPECIAIS QUE REALIZAM OPERACOES MATEMATICAS, LOGICAS OU RELACIONAL
		 	
		 	 
		 	MATEMATICOS CONHECIDOS COMO OPERADORES ARITMETICOS 
		 	------------------------------------------------------------------------------
			|   +  ADIÇÃO																  |
		 	|	-  SUBTRAÇÃO															  |
		 	|	*  MULTIPLICAÇÃO														  |
		 	|	/  DIVISÃO																  |
		 	|	%  MOD ----> RESTO DA DIVISAO											  |
		 	|   |																		  |		
		 	|	--->    22/3 = 7 E SOBRA 1 O MOD "ARMAZENA" A SOBRA, NO CASO % 22/3 = 1   |
		 	|																			  |	
		 	-------------------------------------------------------------------------------
		 		 	
		 	OPERADORES LOGICOS
		 	
		 	&&  AND  O OPERADOR LOGICO && ELE RESULTA EM TRUE OU FALSE, NO QUAL PARA A SENTENÇA PARA SER TRUE TODOS OS CASOS TEM QUEM SER TRUE, TRUE + TRUE = TRUE, FALSE + TRUE = FALSE  
		 	||  OR   O OPERADOR LOGICO || ELE RESULTA EM TRUE OU FALSE, NO QUAL PARA A SENTENÇA PARA SER TRUE PELOMENOS UM CASO TEM QUEM SER TRUE, TRUE + TRUE = TRUE, FALSE + TRUE = TRUE, FALSE + FALSE = FALSE
		 	!   NOT	 O OPERADOR LOGICO !  ELE RESULTA EM TRUE OU FALSE, NO QUAL SEU RESULTA É O INVERSO DO RESULTADO DA SENTEÇA.
		 	
		 	
		 	
		 	OPERADORES RELACIONAL
		 	
		 	==  COMPARA SE DOIS ELEMENTOS SAO IGUAIS 
		 	!= 	COMPARA SE DOIS ELEMENTOS SAO DIFERENTES 
		 	> 	COMPARA SE UM ELEMENTO É MAIOR QUE O OUTRO 
		 	<   COMPARA SE UM ELEMENTO É MENOR QUE O OUTRO
		 	>=  COMPARA SE UM ELEMENTO É MAIOR OU IGUAL QUE O OUTRO
		 	<=	COMPARA SE UM ELEMENTO É MENOR OU IGUAL QUE O OUTRO
		 	
		 	
		 	OPERADORES DE ATRIBUIÇÃO 
		 	
		 	= ATRIBUIR UM VALOR A UM IDENTIFICADOR 
		 	+= ADICIONA E ATRIBUI EQUIVALE A ( A = A + B) FICANDO (A+= B)
		 	-= SUBTRAI E ATRIBUI EQUIVALE A ( A = A - B) FICANDO (A-= B)
		 	*= MULTIPLICA E ATRIBUI EQUIVALE A ( A = A * B) FICANDO (A*= B)
		 	/= DIVIDE E ATRIBUI EQUIVALE A ( A = A / B) FICANDO (A/= B)
		 	
		 	%= ATRIBUI O VALOR DE MOD AO IDENTIFICADOR 
		 	
		 	
		 	
		 	OPERADOR TERNARIO
		 	
		 	A = 2
		 	X = (A % 2 == 0) ? "PAR" : IMPAR;
		 	
		 	ELE EXECUTA UMA SENTENÇA NO QUAL TÁ ESPERANDO TRUE OU FALSE, CASO RESULTE EM TRUE A PRIMEIRA ASPAS É ATRIBUIDA, CASO SEJA FALSE A SEGUNDA ASPAS É ATRIBUIDA
		 	
		 	
		 	
		 	
		 */
		
		
	
} 	
