package Seção_1;

public class Aula_09 {

	// METODO MAIN 
	
	// METODO RESPONSAVEL POR INICIALIZAR O SISTEMA, PONTO DE PARTIDA NA EXECUÇÃO DE UM SISTEMA
	// SEM ELE NAO EXECUTA NADA 
	
	
	// DIGITANDO psvm + ctrl + espaço O METODO É GERADO AUTOMAITCAMENTE 
	// OU DIGITANDO main + ctrl + espaço O METODO É GERADO AUTOMAITCAMENTE 
	
	// SÓ PODE TER APENAS UM METODO MAIN POR SISTEMA
	
	
}
